#### OOPs Task - 09Feb_AssQ 

##### Q1: Create a vehicle class with an init method having instance variables as name_of_vehicle, max_speed and average_of_vehicle.

Ans:01

Here's an example of a Vehicle class with an __init__ method that initializes instance variables for name_of_vehicle, max_speed, and average_of_vehicle:

In [2]:
class vehicle:
    def __init__(self, name_of_vehicle, max_speed, average_of_vechicle):
        self.name_of_vehicle = name_of_vehicle
        self.max_speed =  max_speed
        self.average_of_vechicle = average_of_vechicle
        
        

In this example, the __init__ method takes three parameters: name_of_vehicle, max_speed, and average_of_vehicle. The method initializes the instance variables by assigning the parameter values to them using the self keyword.

- You can create an instance of the Vehicle class and access its attributes like this:

In [4]:
car = vehicle("Tesla Model S", 250, 150)



In [5]:
print(car.max_speed)

250


In [6]:
print(car.average_of_vechicle)

150


In [7]:
print(car.name_of_vehicle)

Tesla Model S


Here, a car object is created with the name "Tesla Model S", a maximum speed of 250, and an average speed of 150. The instance variables can be accessed using dot notation (object_name.attribute_name).

##### Q2. Create a child class car from the vehicle class created in Que 1, which will inherit the vehicle class.
##### Create a method named seating_capacity which takes capacity as an argument and returns the name of the vehicle and its seating capacity.

Ans:02

Here's the code to create a child class Car that inherits from the Vehicle class, and includes a seating_capacity method:


In [11]:
class vehicle:
    def __init__(self, name_of_vehicle, max_speed, average_of_vechicle):
        self.name_of_vehicle = name_of_vehicle
        self.max_speed =  max_speed
        self.average_of_vechicle = average_of_vechicle
        
class Car(vehicle):
    def seating_capacity(self, capacity):
        return f"The {self.name_of_vehicle} has a seating capaciy of {capacity}."
    
#Now,

car = Car("Tesla Model S", 250, 150)
print(car.seating_capacity(5))

The Tesla Model S has a seating capaciy of 5.


- In this code, we first define the Vehicle class with the __init__ method that initializes the instance variables name_of_vehicle, max_speed, and average_of_vehicle.

- Then, we define the Car class as a child class of Vehicle using class Car(Vehicle):. This means that the Car class inherits all the attributes and methods from the Vehicle class.

- The Car class includes the seating_capacity method which takes a capacity argument and returns a string indicating the name of the vehicle and its seating capacity.

- In the example usage, we create a car object of the Car class and pass the appropriate arguments to the __init__ method to initialize the instance variables. Then, we call the seating_capacity method on the car object and pass the seating capacity (5 in this case). The method returns a string that indicates the name of the vehicle and its seating capacity, which we then print.

##### Q3. What is multiple inheritance? Write a python code to demonstrate multiple inheritance.

Ans:03

- Multiple inheritance is a feature in object-oriented programming where a class can inherit attributes and methods from multiple parent classes. This means that a child class can inherit characteristics from multiple base or parent classes, allowing for code reuse and flexibility.

Here's an example of Python code that demonstrates multiple inheritance:

In [12]:
class Animal:
    def speak(self):
        print("The animal speaks.")
        
class Mammal:
    def feed_milk(self):
        print("The mammal feeds milk.")

class Dog(Animal, Mammal):
    def bark(self):
        print("The dog barks.")

In [13]:
# create an instance of dog class

dog = Dog()

In [15]:
# call methods inherited from animal class

dog.speak()

The animal speaks.


In [16]:
# call methods inherited from mammal class

dog.feed_milk()

The mammal feeds milk.


In [18]:
# call method specific to Dog class

dog.bark()

The dog barks.


- In this code, we define three classes: Animal, Mammal, and Dog. The Animal class has a speak method, the Mammal class has a feed_milk method, and the Dog class has a bark method.

- The Dog class is derived from both the Animal and Mammal classes using multiple inheritance. As a result, the Dog class inherits the speak method from the Animal class and the feed_milk method from the Mammal class.

- We create an instance of the Dog class and call the inherited methods speak and feed_milk as well as the method specific to the Dog class, bark.

- Multiple inheritance allows us to combine the characteristics and behaviors of different classes to create more specialized and flexible classes. However, it's important to use multiple inheritance judiciously to avoid potential complexities and conflicts in the inheritance hierarchy.

##### Q4. What are getter and setter in python? Create a class and create a getter and a setter method in this class.

Ans:04



- In Python, getters and setters are methods that provide access to the attributes of a class while encapsulating the underlying implementation details. They are used to retrieve (get) and modify (set) the values of private or protected instance variables of a class, allowing controlled access to the attributes.

Here's an example of a Python class with a getter and a setter method:

In [6]:
class Person:
    def __init__(self, name):
        self._name = name
        
    def get_name(self):
        return self._name
    
    def set_name(self, new_name): 
        self._name = new_name
        
# Create an instance of the Person Class
person = Person("Alice")

# Use the getter method:
print(person.get_name())

Alice


In [7]:
# Use the setter method:
print(person.set_name("Bob"))

None


In [8]:
# Use the getter method after setting a new name

print(person.get_name())

Bob


- In this example, we define a Person class with a private attribute _name. The getter method get_name retrieves the value of _name and returns it. The setter method set_name takes a new_name parameter and assigns it to the _name attribute.

- When we create an instance of the Person class, we initialize the _name attribute with the name "Alice". We can then use the getter method get_name to retrieve the name and the setter method set_name to change the name to "Bob". Finally, we use the getter method again to retrieve and print the updated name.

- By using getters and setters, we can control the access to the attributes of a class, enforce validation or business logic, and maintain encapsulation by hiding the internal implementation details of the class.

##### Q5.What is method overriding in python? Write a python code to demonstrate method overriding.

Ans:05

- Method overriding in Python refers to the ability of a subclass to provide its own implementation of a method that is already defined in its superclass. When a method is overridden, the subclass redefines the behavior of the method inherited from the superclass.

Here's an example of Python code that demonstrates method overriding:

In [11]:
class Shape:
    def area(self):
        print("Calculating area of a generic shape.")
        
class Rectangle(Shape):
    def area(self):
        length = 5
        width = 3
        area = length * width
        print(f"The area of the rectangle is {area}.")

In [12]:
# Creating an instance of the rectangle class:

rectangle = Rectangle()

In [14]:
# Now call the overridden method:

rectangle.area()

The area of the rectangle is 15.


- In this code, we have a Shape class with a method area that provides a generic implementation for calculating the area of a shape. The Rectangle class is a subclass of Shape and overrides the area method with its own implementation specific to rectangles.

- The Rectangle class defines the area method, which calculates the area of a rectangle with a length of 5 and a width of 3. When we create an instance of the Rectangle class and call the area method, it executes the overridden method in the Rectangle class rather than the one inherited from the Shape class.

- Method overriding allows subclasses to provide specialized behavior for specific methods, enabling polymorphism and the ability to tailor functionality to different subclasses while maintaining a common interface.

> Note: In Python, method overriding is achieved by simply defining a method with the same name in the subclass, which replaces the method inherited from the superclass.